version: '3.8'

services:
  postgres-test:
    image: postgres:18-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: nestjs_template_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nestjs_template_test']
      interval: 5s
      timeout: 5s
      retries: 5
