allowBuilds:
  '@apollo/protobufjs': true
  '@scarf/scarf': true
  '@sentry/node-cpu-profiler': true
  cpu-features: true
  msgpackr-extract: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@sisques-labs/nestjs-kit@1.6.1'
