#!/usr/bin/env bash
# Renames this template repo into a new service.
#
# Usage:
#   scripts/rename-service.sh <new-service-name> ["New Service Title"]
#
# <new-service-name> must be kebab-case (e.g. "orders-api"). It replaces every
# occurrence of "nestjs-template" across the repo — package name, Docker image
# names, Kafka client id/topic prefix defaults, Sentry/metrics/MCP identifiers,
# docker-compose database names, etc. The title (used in the Swagger page and
# README heading) defaults to a Title Case version of the name if omitted.
set -euo pipefail

OLD_NAME="nestjs-template"
OLD_TITLE="NestJS Template"

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <new-service-name-kebab-case> [\"New Service Title\"]" >&2
  exit 1
fi

NEW_NAME="$1"
if [[ ! "$NEW_NAME" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
  echo "Error: <new-service-name> must be kebab-case (lowercase letters, digits, hyphens), e.g. 'orders-api'." >&2
  exit 1
fi

if [[ $# -ge 2 ]]; then
  NEW_TITLE="$2"
else
  NEW_TITLE=$(echo "$NEW_NAME" | awk -F- '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1' OFS=' ')
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "Renaming template: '$OLD_NAME' -> '$NEW_NAME' (title: '$NEW_TITLE')"

# Exclude the lockfile (regenerated by `pnpm install` below) and this script
# itself (it would otherwise rewrite its own OLD_NAME/OLD_TITLE constants).
SELF_PATH="scripts/rename-service.sh"

git ls-files | grep -v -E "^(pnpm-lock\.yaml|${SELF_PATH})$" | while IFS= read -r f; do
  [[ -f "$f" ]] || continue
  if grep -qI "$OLD_TITLE" "$f" 2>/dev/null; then
    sed -i.bak "s/$OLD_TITLE/$NEW_TITLE/g" "$f" && rm -f "$f.bak"
  fi
  if grep -qI "$OLD_NAME" "$f" 2>/dev/null; then
    sed -i.bak "s/$OLD_NAME/$NEW_NAME/g" "$f" && rm -f "$f.bak"
  fi
done

echo "Done. Next steps:"
echo "  1. Review the diff: git diff"
echo "  2. pnpm install   # refreshes the lockfile for the new package name"
echo "  3. Update the GitHub repository name/description if you're creating a new repo"
echo "  4. Double-check .github/workflows/release.yml and release-train.yml image names"
echo "  5. Rewrite .env.example DATABASE_DATABASE / docker-compose*.yml volumes if you want a different DB name"
